# Generated by Django 5.0.4 on 2024-05-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('kode_matkul', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_matkul', models.CharField(max_length=255)),
                ('sks', models.IntegerField()),
                ('dosen_pengampu', models.CharField(max_length=255)),
            ],
        ),
    ]
